package org.sef4j.jdbc.util;

import java.sql.Statement;

public class StatementUtils {

    public static String autoGeneratedKeysToString(int autoGeneratedKeys) {
        switch(autoGeneratedKeys) {
        case Statement.RETURN_GENERATED_KEYS: return "RETURN_GENERATED_KEYS";
        case Statement.NO_GENERATED_KEYS: return "NO_GENERATED_KEYS";
        default: return "UNKNOW-" + autoGeneratedKeys; 
        }
    }
    
}
